#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-/home/szu2070436088/2510044040/CV-SincNet}"
PYTHON="${PYTHON:-/home/szu2070436088/.conda/envs/CVS-RFFI/bin/python}"
TRAIN_SCRIPT="${TRAIN_SCRIPT:-${ROOT}/code/train.py}"
RUN_ID="${RUN_ID:-cen51_pure_fewshot_step_sampler_20260610_140100}"
LOG_ROOT="${LOG_ROOT:-${ROOT}/logs/${RUN_ID}}"
RUNS_ROOT="${RUNS_ROOT:-${ROOT}/runs/${RUN_ID}}"
MAX_TRAIN_PER_GPU="${MAX_TRAIN_PER_GPU:-2}"
DRY_RUN="${DRY_RUN:-0}"
ONLY_CANDIDATE="${ONLY_CANDIDATE:-}"

for arg in "$@"; do
  case "${arg}" in
    --dry-run) DRY_RUN=1 ;;
    --only=*) ONLY_CANDIDATE="${arg#--only=}" ;;
    *) echo "[ERROR] unknown argument: ${arg}" >&2; exit 2 ;;
  esac
done

gpu_process_count() {
  local gpu="$1"
  nvidia-smi --id="${gpu}" --query-compute-apps=pid --format=csv,noheader,nounits 2>/dev/null \
    | sed '/^$/d' | wc -l | tr -d ' '
}

print_cmd() { printf '%q ' "$@"; printf '\n'; }

should_skip() {
  local candidate_id="$1" run_name="$2"
  [[ -n "${ONLY_CANDIDATE}" && "${candidate_id}" != "${ONLY_CANDIDATE}" && "${run_name}" != "${ONLY_CANDIDATE}" ]]
}

declare -A LAUNCHED_BY_GPU=()

run_candidate() {
  local candidate_id="$1" run_name="$2" regime="$3" gpu="$4"
  shift 4
  local run_dir="${RUNS_ROOT}/${run_name}"
  local log_path="${LOG_ROOT}/${run_name}.out"
  local cmd=(env "CUDA_VISIBLE_DEVICES=${gpu}" "PYTHONPATH=${ROOT}/code:${ROOT}:${PYTHONPATH:-}" "${PYTHON}" -u "${TRAIN_SCRIPT}" "$@"
    --run_name "${run_name}"
    --latest_save_path "${run_dir}/latest_model.pth"
    --best_save_path "${run_dir}/best_val_model.pth"
    --best_primary_save_path "${run_dir}/best_primary_ood_model.pth"
    --best_unseen_day_unseen_rx_save_path "${run_dir}/best_strict_udu_model.pth"
    --best_worst_rx_save_path "${run_dir}/best_worst_rx_model.pth"
    --ema_save_path "${run_dir}/ema_model.pth"
    --swa_save_path "${run_dir}/swa_model.pth"
    --swad_save_path "${run_dir}/swad_model.pth")

  if should_skip "${candidate_id}" "${run_name}"; then return 0; fi
  echo "[CEN51-PFS2] candidate=${candidate_id} run=${run_name} regime=${regime} gpu=${gpu} dry_run=${DRY_RUN} max_train_per_gpu=${MAX_TRAIN_PER_GPU}"
  printf '[CEN51-PFS2-CMD]'
  print_cmd "${cmd[@]}"
  if [[ "${DRY_RUN}" == "1" ]]; then return 0; fi
  if [[ -e "${run_dir}" || -e "${log_path}" ]]; then
    mkdir -p "${LOG_ROOT}"
    printf "%s\t%s\t%s\t%s\t%s\n" "${candidate_id}" "${run_name}" "BLOCKED_PATH_COLLISION" "${log_path}" "${run_dir}" | tee -a "${LOG_ROOT}/blocked.tsv"
    return 0
  fi
  local current_count local_count
  current_count="$(gpu_process_count "${gpu}")"
  local_count="${LAUNCHED_BY_GPU[${gpu}]:-0}"
  if (( current_count + local_count >= MAX_TRAIN_PER_GPU )); then
    mkdir -p "${LOG_ROOT}"
    printf "%s\t%s\t%s\tgpu=%s active_count=%s local_count=%s max=%s\n" "${candidate_id}" "${run_name}" "BLOCKED_CAPACITY" "${gpu}" "${current_count}" "${local_count}" "${MAX_TRAIN_PER_GPU}" | tee -a "${LOG_ROOT}/blocked.tsv"
    return 0
  fi
  mkdir -p "${LOG_ROOT}" "${run_dir}"
  nohup "${cmd[@]}" > "${log_path}" 2>&1 &
  local pid="$!"
  LAUNCHED_BY_GPU["${gpu}"]=$(( local_count + 1 ))
  printf "%s\t%s\t%s\t%s\t%s\t%s\n" "${candidate_id}" "${run_name}" "${gpu}" "${pid}" "${log_path}" "${run_dir}" | tee -a "${LOG_ROOT}/launch_pids.tsv"
}

if [[ "${DRY_RUN}" != "1" ]]; then
  [[ -f "${TRAIN_SCRIPT}" ]] || { echo "[ERROR] missing train script: ${TRAIN_SCRIPT}" >&2; exit 2; }
fi
cd "${ROOT}"
echo "[CEN51-PFS2] run_id=${RUN_ID} dry_run=${DRY_RUN} max_train_per_gpu=${MAX_TRAIN_PER_GPU}"

run_candidate PFS01_FS005_FIT64_WEAKSAT CEN51_PFS2_FS005_FIT64_WEAKSAT_seed2028 pure_fewshot_lt100 0 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  16 \
  --epochs \
  170 \
  --train_steps_per_epoch \
  64 \
  --lr \
  0.0003 \
  --lr_min \
  1e-06 \
  --wd \
  5e-05 \
  --wisig_train_shots_per_class \
  5 \
  --wisig_train_shot_strategy \
  rx_day_balanced \
  --swad_start_epoch \
  55 \
  --swad_tolerance \
  0.85 \
  --no_use_aug \
  --no_use_mixstyle \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --aug_p_pa \
  0.0 \
  --aug_p_dac \
  0.0 \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.32 \
  --lambda_adv \
  0.06 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.01 \
  --lambda_cons \
  0.0 \
  --lambda_group_ce \
  0.0 \
  --lambda_proto \
  0.0 \
  --lambda_supcon_id \
  0.0 \
  --lambda_fishr \
  0.0 \
  --lambda_feature_norm_guard \
  0.00045 \
  --feature_norm_guard_mode \
  hinge \
  --feature_norm_guard_target \
  8 \
  --min_batch_domains_for_domain_loss \
  2 \
  --min_batch_domain_frac \
  0.1 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.06 \
  --sat_view_prob \
  0.06 \
  --sat_train_scenarios \
  clear_leo,mixed_orbit \
  --sat_view_schedule \
  1@0.06:clear_leo,mixed_orbit

run_candidate PFS02_FS005_FIT96_WEAKSAT CEN51_PFS2_FS005_FIT96_WEAKSAT_seed2028 pure_fewshot_lt100 1 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  16 \
  --epochs \
  140 \
  --train_steps_per_epoch \
  96 \
  --lr \
  0.0003 \
  --lr_min \
  1e-06 \
  --wd \
  5e-05 \
  --wisig_train_shots_per_class \
  5 \
  --wisig_train_shot_strategy \
  rx_day_balanced \
  --swad_start_epoch \
  55 \
  --swad_tolerance \
  0.85 \
  --no_use_aug \
  --no_use_mixstyle \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --aug_p_pa \
  0.0 \
  --aug_p_dac \
  0.0 \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.32 \
  --lambda_adv \
  0.06 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.01 \
  --lambda_cons \
  0.0 \
  --lambda_group_ce \
  0.0 \
  --lambda_proto \
  0.0 \
  --lambda_supcon_id \
  0.0 \
  --lambda_fishr \
  0.0 \
  --lambda_feature_norm_guard \
  0.00045 \
  --feature_norm_guard_mode \
  hinge \
  --feature_norm_guard_target \
  8 \
  --min_batch_domains_for_domain_loss \
  2 \
  --min_batch_domain_frac \
  0.1 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.06 \
  --sat_view_prob \
  0.06 \
  --sat_train_scenarios \
  clear_leo,mixed_orbit \
  --sat_view_schedule \
  1@0.06:clear_leo,mixed_orbit

run_candidate PFS03_FS005_RIEI_STRONG64 CEN51_PFS2_FS005_RIEI_STRONG64_seed2028 pure_fewshot_lt100 2 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  16 \
  --epochs \
  170 \
  --train_steps_per_epoch \
  64 \
  --lr \
  0.00025 \
  --lr_min \
  1e-06 \
  --wd \
  8e-05 \
  --wisig_train_shots_per_class \
  5 \
  --wisig_train_shot_strategy \
  rx_day_balanced \
  --swad_start_epoch \
  55 \
  --swad_tolerance \
  0.85 \
  --no_use_aug \
  --no_use_mixstyle \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --aug_p_pa \
  0.0 \
  --aug_p_dac \
  0.0 \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.55 \
  --lambda_adv \
  0.22 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.04 \
  --lambda_cons \
  0.0 \
  --lambda_group_ce \
  0.0 \
  --lambda_proto \
  0.0 \
  --lambda_supcon_id \
  0.0 \
  --lambda_fishr \
  0.0 \
  --lambda_feature_norm_guard \
  0.0015 \
  --feature_norm_guard_mode \
  hinge \
  --feature_norm_guard_target \
  6.5 \
  --min_batch_domains_for_domain_loss \
  2 \
  --min_batch_domain_frac \
  0.1 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.04 \
  --sat_view_prob \
  0.04 \
  --sat_train_scenarios \
  clear_leo,mixed_orbit \
  --sat_view_schedule \
  1@0.04:clear_leo,mixed_orbit \
  --stage1_epochs \
  20 \
  --stage2_epochs \
  55 \
  --stage3_ramp_epochs \
  20 \
  --late_stable_start \
  115 \
  --late_stable_ramp_epochs \
  25 \
  --late_adv_min_scale \
  0.85 \
  --late_cons_min_scale \
  0.0 \
  --late_group_ce_min_scale \
  0.0

run_candidate PFS04_FS005_FIT64_RANDOM CEN51_PFS2_FS005_FIT64_RANDOM_seed2028 pure_fewshot_lt100 3 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  16 \
  --epochs \
  170 \
  --train_steps_per_epoch \
  64 \
  --lr \
  0.0003 \
  --lr_min \
  1e-06 \
  --wd \
  5e-05 \
  --wisig_train_shots_per_class \
  5 \
  --wisig_train_shot_strategy \
  random \
  --swad_start_epoch \
  55 \
  --swad_tolerance \
  0.85 \
  --no_use_aug \
  --no_use_mixstyle \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --aug_p_pa \
  0.0 \
  --aug_p_dac \
  0.0 \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.32 \
  --lambda_adv \
  0.06 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.01 \
  --lambda_cons \
  0.0 \
  --lambda_group_ce \
  0.0 \
  --lambda_proto \
  0.0 \
  --lambda_supcon_id \
  0.0 \
  --lambda_fishr \
  0.0 \
  --lambda_feature_norm_guard \
  0.00045 \
  --feature_norm_guard_mode \
  hinge \
  --feature_norm_guard_target \
  8 \
  --min_batch_domains_for_domain_loss \
  2 \
  --min_batch_domain_frac \
  0.1 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.06 \
  --sat_view_prob \
  0.06 \
  --sat_train_scenarios \
  clear_leo,mixed_orbit \
  --sat_view_schedule \
  1@0.06:clear_leo,mixed_orbit

run_candidate PFS05_FS010_FIT48_WEAKSAT CEN51_PFS2_FS010_FIT48_WEAKSAT_seed2028 pure_fewshot_lt100 4 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  16 \
  --epochs \
  170 \
  --train_steps_per_epoch \
  48 \
  --lr \
  0.0003 \
  --lr_min \
  1e-06 \
  --wd \
  5e-05 \
  --wisig_train_shots_per_class \
  10 \
  --wisig_train_shot_strategy \
  rx_day_balanced \
  --swad_start_epoch \
  65 \
  --swad_tolerance \
  0.85 \
  --no_use_aug \
  --no_use_mixstyle \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --aug_p_pa \
  0.0 \
  --aug_p_dac \
  0.0 \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.36 \
  --lambda_adv \
  0.08 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.01 \
  --lambda_cons \
  0.0 \
  --lambda_group_ce \
  0.0 \
  --lambda_proto \
  0.0 \
  --lambda_supcon_id \
  0.0 \
  --lambda_fishr \
  0.0 \
  --lambda_feature_norm_guard \
  0.00035 \
  --feature_norm_guard_mode \
  hinge \
  --feature_norm_guard_target \
  8 \
  --min_batch_domains_for_domain_loss \
  2 \
  --min_batch_domain_frac \
  0.1 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.08 \
  --sat_view_prob \
  0.08 \
  --sat_train_scenarios \
  clear_leo,mixed_orbit \
  --sat_view_schedule \
  1@0.08:clear_leo,mixed_orbit

run_candidate PFS06_FS010_FIT80_WEAKSAT CEN51_PFS2_FS010_FIT80_WEAKSAT_seed2028 pure_fewshot_lt100 5 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  16 \
  --epochs \
  140 \
  --train_steps_per_epoch \
  80 \
  --lr \
  0.0003 \
  --lr_min \
  1e-06 \
  --wd \
  5e-05 \
  --wisig_train_shots_per_class \
  10 \
  --wisig_train_shot_strategy \
  rx_day_balanced \
  --swad_start_epoch \
  65 \
  --swad_tolerance \
  0.85 \
  --no_use_aug \
  --no_use_mixstyle \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --aug_p_pa \
  0.0 \
  --aug_p_dac \
  0.0 \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.36 \
  --lambda_adv \
  0.08 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.01 \
  --lambda_cons \
  0.0 \
  --lambda_group_ce \
  0.0 \
  --lambda_proto \
  0.0 \
  --lambda_supcon_id \
  0.0 \
  --lambda_fishr \
  0.0 \
  --lambda_feature_norm_guard \
  0.00035 \
  --feature_norm_guard_mode \
  hinge \
  --feature_norm_guard_target \
  8 \
  --min_batch_domains_for_domain_loss \
  2 \
  --min_batch_domain_frac \
  0.1 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.08 \
  --sat_view_prob \
  0.08 \
  --sat_train_scenarios \
  clear_leo,mixed_orbit \
  --sat_view_schedule \
  1@0.08:clear_leo,mixed_orbit

run_candidate PFS07_FS010_RIEI_STRONG64 CEN51_PFS2_FS010_RIEI_STRONG64_seed2028 pure_fewshot_lt100 6 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  16 \
  --epochs \
  170 \
  --train_steps_per_epoch \
  64 \
  --lr \
  0.00025 \
  --lr_min \
  1e-06 \
  --wd \
  8e-05 \
  --wisig_train_shots_per_class \
  10 \
  --wisig_train_shot_strategy \
  rx_day_balanced \
  --swad_start_epoch \
  65 \
  --swad_tolerance \
  0.85 \
  --no_use_aug \
  --no_use_mixstyle \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --aug_p_pa \
  0.0 \
  --aug_p_dac \
  0.0 \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.6 \
  --lambda_adv \
  0.28 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.04 \
  --lambda_cons \
  0.0 \
  --lambda_group_ce \
  0.0 \
  --lambda_proto \
  0.0 \
  --lambda_supcon_id \
  0.0 \
  --lambda_fishr \
  0.0 \
  --lambda_feature_norm_guard \
  0.001 \
  --feature_norm_guard_mode \
  hinge \
  --feature_norm_guard_target \
  7 \
  --min_batch_domains_for_domain_loss \
  2 \
  --min_batch_domain_frac \
  0.1 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.06 \
  --sat_view_prob \
  0.06 \
  --sat_train_scenarios \
  clear_leo,mixed_orbit \
  --sat_view_schedule \
  1@0.06:clear_leo,mixed_orbit \
  --stage1_epochs \
  18 \
  --stage2_epochs \
  50 \
  --stage3_ramp_epochs \
  20 \
  --late_stable_start \
  110 \
  --late_stable_ramp_epochs \
  25 \
  --late_adv_min_scale \
  0.85 \
  --late_cons_min_scale \
  0.0 \
  --late_group_ce_min_scale \
  0.0

run_candidate PFS08_FS010_FIT48_RANDOM CEN51_PFS2_FS010_FIT48_RANDOM_seed2028 pure_fewshot_lt100 7 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  16 \
  --epochs \
  170 \
  --train_steps_per_epoch \
  48 \
  --lr \
  0.0003 \
  --lr_min \
  1e-06 \
  --wd \
  5e-05 \
  --wisig_train_shots_per_class \
  10 \
  --wisig_train_shot_strategy \
  random \
  --swad_start_epoch \
  65 \
  --swad_tolerance \
  0.85 \
  --no_use_aug \
  --no_use_mixstyle \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --aug_p_pa \
  0.0 \
  --aug_p_dac \
  0.0 \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.36 \
  --lambda_adv \
  0.08 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.01 \
  --lambda_cons \
  0.0 \
  --lambda_group_ce \
  0.0 \
  --lambda_proto \
  0.0 \
  --lambda_supcon_id \
  0.0 \
  --lambda_fishr \
  0.0 \
  --lambda_feature_norm_guard \
  0.00035 \
  --feature_norm_guard_mode \
  hinge \
  --feature_norm_guard_target \
  8 \
  --min_batch_domains_for_domain_loss \
  2 \
  --min_batch_domain_frac \
  0.1 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.08 \
  --sat_view_prob \
  0.08 \
  --sat_train_scenarios \
  clear_leo,mixed_orbit \
  --sat_view_schedule \
  1@0.08:clear_leo,mixed_orbit

run_candidate PFS09_FS020_CLEAN64_RXDAY CEN51_PFS2_FS020_CLEAN64_RXDAY_seed2028 pure_fewshot_lt100 0 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  32 \
  --epochs \
  180 \
  --train_steps_per_epoch \
  64 \
  --lr \
  0.00025 \
  --lr_min \
  1e-06 \
  --wd \
  7e-05 \
  --wisig_train_shots_per_class \
  20 \
  --wisig_train_shot_strategy \
  rx_day_balanced \
  --swad_start_epoch \
  75 \
  --swad_tolerance \
  0.7 \
  --use_aug \
  --aug_scale_min \
  0.03 \
  --aug_scale_max \
  0.18 \
  --late_aug_min_scale \
  0.14 \
  --use_mixstyle \
  --mixstyle_layers \
  time_down,t1 \
  --mixstyle_mix \
  same_tx_crossdomain \
  --mixstyle_fallback \
  skip \
  --mixstyle_p \
  0.03 \
  --mixstyle_strength \
  0.16 \
  --mixstyle_late_start \
  120 \
  --mixstyle_late_ramp_epochs \
  40 \
  --mixstyle_late_min_p \
  0.02 \
  --mixstyle_late_min_strength \
  0.12 \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.42 \
  --lambda_adv \
  0.16 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.015 \
  --lambda_cons \
  0.008 \
  --lambda_group_ce \
  0.008 \
  --group_ce_mode \
  smooth_dro_capped \
  --group_ce_min_domains \
  2 \
  --group_ce_top_frac \
  0.18 \
  --groupdro_tau \
  0.35 \
  --groupdro_cap \
  0.45 \
  --use_proto_memory \
  --lambda_proto \
  0.001 \
  --proto_momentum \
  0.95 \
  --lambda_supcon_id \
  0.001 \
  --supcon_temp \
  0.12 \
  --lambda_fishr \
  0.0 \
  --fishr_min_domains \
  2 \
  --lambda_feature_norm_guard \
  8e-05 \
  --feature_norm_guard_mode \
  l2 \
  --feature_norm_guard_target \
  0.0 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --no_use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.0 \
  --sat_view_prob \
  0.0

run_candidate PFS10_FS020_SAT64_RXDAY CEN51_PFS2_FS020_SAT64_RXDAY_seed2028 pure_fewshot_lt100 1 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  32 \
  --epochs \
  180 \
  --train_steps_per_epoch \
  64 \
  --lr \
  0.00025 \
  --lr_min \
  1e-06 \
  --wd \
  7e-05 \
  --wisig_train_shots_per_class \
  20 \
  --wisig_train_shot_strategy \
  rx_day_balanced \
  --swad_start_epoch \
  75 \
  --swad_tolerance \
  0.7 \
  --use_aug \
  --aug_scale_min \
  0.03 \
  --aug_scale_max \
  0.18 \
  --late_aug_min_scale \
  0.14 \
  --use_mixstyle \
  --mixstyle_layers \
  time_down,t1 \
  --mixstyle_mix \
  same_tx_crossdomain \
  --mixstyle_fallback \
  skip \
  --mixstyle_p \
  0.03 \
  --mixstyle_strength \
  0.16 \
  --mixstyle_late_start \
  120 \
  --mixstyle_late_ramp_epochs \
  40 \
  --mixstyle_late_min_p \
  0.02 \
  --mixstyle_late_min_strength \
  0.12 \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.42 \
  --lambda_adv \
  0.15 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.015 \
  --lambda_cons \
  0.008 \
  --lambda_group_ce \
  0.008 \
  --group_ce_mode \
  smooth_dro_capped \
  --group_ce_min_domains \
  2 \
  --group_ce_top_frac \
  0.18 \
  --groupdro_tau \
  0.35 \
  --groupdro_cap \
  0.45 \
  --use_proto_memory \
  --lambda_proto \
  0.001 \
  --proto_momentum \
  0.95 \
  --lambda_supcon_id \
  0.001 \
  --supcon_temp \
  0.12 \
  --lambda_fishr \
  0.0 \
  --fishr_min_domains \
  2 \
  --lambda_feature_norm_guard \
  6e-05 \
  --feature_norm_guard_mode \
  l2 \
  --feature_norm_guard_target \
  0.0 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.1 \
  --sat_view_prob \
  0.1 \
  --sat_train_scenarios \
  clear_leo,mixed_orbit \
  --sat_view_schedule \
  '1@0.10:clear_leo,mixed_orbit;145@0.06:clear_leo,mixed_orbit'

run_candidate PFS11_FS020_SAT96_RXDAY CEN51_PFS2_FS020_SAT96_RXDAY_seed2028 pure_fewshot_lt100 2 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  32 \
  --epochs \
  180 \
  --train_steps_per_epoch \
  96 \
  --lr \
  0.00025 \
  --lr_min \
  1e-06 \
  --wd \
  7e-05 \
  --wisig_train_shots_per_class \
  20 \
  --wisig_train_shot_strategy \
  rx_day_balanced \
  --swad_start_epoch \
  75 \
  --swad_tolerance \
  0.7 \
  --use_aug \
  --aug_scale_min \
  0.03 \
  --aug_scale_max \
  0.18 \
  --late_aug_min_scale \
  0.14 \
  --use_mixstyle \
  --mixstyle_layers \
  time_down,t1 \
  --mixstyle_mix \
  same_tx_crossdomain \
  --mixstyle_fallback \
  skip \
  --mixstyle_p \
  0.03 \
  --mixstyle_strength \
  0.16 \
  --mixstyle_late_start \
  120 \
  --mixstyle_late_ramp_epochs \
  40 \
  --mixstyle_late_min_p \
  0.02 \
  --mixstyle_late_min_strength \
  0.12 \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.42 \
  --lambda_adv \
  0.15 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.015 \
  --lambda_cons \
  0.008 \
  --lambda_group_ce \
  0.008 \
  --group_ce_mode \
  smooth_dro_capped \
  --group_ce_min_domains \
  2 \
  --group_ce_top_frac \
  0.18 \
  --groupdro_tau \
  0.35 \
  --groupdro_cap \
  0.45 \
  --use_proto_memory \
  --lambda_proto \
  0.001 \
  --proto_momentum \
  0.95 \
  --lambda_supcon_id \
  0.001 \
  --supcon_temp \
  0.12 \
  --lambda_fishr \
  0.0 \
  --fishr_min_domains \
  2 \
  --lambda_feature_norm_guard \
  6e-05 \
  --feature_norm_guard_mode \
  l2 \
  --feature_norm_guard_target \
  0.0 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.1 \
  --sat_view_prob \
  0.1 \
  --sat_train_scenarios \
  clear_leo,mixed_orbit \
  --sat_view_schedule \
  '1@0.10:clear_leo,mixed_orbit;145@0.06:clear_leo,mixed_orbit'

run_candidate PFS12_FS030_CLEAN56_RXDAY CEN51_PFS2_FS030_CLEAN56_RXDAY_seed2028 pure_fewshot_lt100 3 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  32 \
  --epochs \
  180 \
  --train_steps_per_epoch \
  56 \
  --lr \
  0.00025 \
  --lr_min \
  1e-06 \
  --wd \
  7e-05 \
  --wisig_train_shots_per_class \
  30 \
  --wisig_train_shot_strategy \
  rx_day_balanced \
  --swad_start_epoch \
  85 \
  --swad_tolerance \
  0.7 \
  --use_aug \
  --aug_scale_min \
  0.03 \
  --aug_scale_max \
  0.22 \
  --late_aug_min_scale \
  0.16 \
  --use_mixstyle \
  --mixstyle_layers \
  time_down,t1 \
  --mixstyle_mix \
  same_tx_crossdomain \
  --mixstyle_fallback \
  skip \
  --mixstyle_p \
  0.05 \
  --mixstyle_strength \
  0.22 \
  --mixstyle_late_start \
  130 \
  --mixstyle_late_ramp_epochs \
  40 \
  --mixstyle_late_min_p \
  0.0225 \
  --mixstyle_late_min_strength \
  0.121 \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.48 \
  --lambda_adv \
  0.2 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.015 \
  --lambda_cons \
  0.012 \
  --lambda_group_ce \
  0.014 \
  --group_ce_mode \
  smooth_dro_capped \
  --group_ce_min_domains \
  2 \
  --group_ce_top_frac \
  0.22 \
  --groupdro_tau \
  0.42 \
  --groupdro_cap \
  0.55 \
  --use_proto_memory \
  --lambda_proto \
  0.002 \
  --proto_momentum \
  0.95 \
  --lambda_supcon_id \
  0.002 \
  --supcon_temp \
  0.12 \
  --lambda_fishr \
  0.0002 \
  --fishr_min_domains \
  2 \
  --lambda_feature_norm_guard \
  6e-05 \
  --feature_norm_guard_mode \
  l2 \
  --feature_norm_guard_target \
  0.0 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --no_use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.0 \
  --sat_view_prob \
  0.0

run_candidate PFS13_FS030_SAT56_RXDAY CEN51_PFS2_FS030_SAT56_RXDAY_seed2028 pure_fewshot_lt100 4 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  32 \
  --epochs \
  180 \
  --train_steps_per_epoch \
  56 \
  --lr \
  0.00025 \
  --lr_min \
  1e-06 \
  --wd \
  7e-05 \
  --wisig_train_shots_per_class \
  30 \
  --wisig_train_shot_strategy \
  rx_day_balanced \
  --swad_start_epoch \
  85 \
  --swad_tolerance \
  0.7 \
  --use_aug \
  --aug_scale_min \
  0.03 \
  --aug_scale_max \
  0.22 \
  --late_aug_min_scale \
  0.16 \
  --use_mixstyle \
  --mixstyle_layers \
  time_down,t1 \
  --mixstyle_mix \
  same_tx_crossdomain \
  --mixstyle_fallback \
  skip \
  --mixstyle_p \
  0.05 \
  --mixstyle_strength \
  0.22 \
  --mixstyle_late_start \
  130 \
  --mixstyle_late_ramp_epochs \
  40 \
  --mixstyle_late_min_p \
  0.0225 \
  --mixstyle_late_min_strength \
  0.121 \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.48 \
  --lambda_adv \
  0.19 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.015 \
  --lambda_cons \
  0.012 \
  --lambda_group_ce \
  0.014 \
  --group_ce_mode \
  smooth_dro_capped \
  --group_ce_min_domains \
  2 \
  --group_ce_top_frac \
  0.22 \
  --groupdro_tau \
  0.42 \
  --groupdro_cap \
  0.55 \
  --use_proto_memory \
  --lambda_proto \
  0.002 \
  --proto_momentum \
  0.95 \
  --lambda_supcon_id \
  0.002 \
  --supcon_temp \
  0.12 \
  --lambda_fishr \
  0.0002 \
  --fishr_min_domains \
  2 \
  --lambda_feature_norm_guard \
  5e-05 \
  --feature_norm_guard_mode \
  l2 \
  --feature_norm_guard_target \
  0.0 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.14 \
  --sat_view_prob \
  0.14 \
  --sat_train_scenarios \
  clear_leo,mixed_orbit \
  --sat_view_schedule \
  '1@0.14:clear_leo,mixed_orbit;145@0.08:clear_leo,mixed_orbit'

run_candidate PFS14_FS050_SAT48_RXDAY CEN51_PFS2_FS050_SAT48_RXDAY_seed2028 pure_fewshot_lt100 5 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  64 \
  --epochs \
  190 \
  --train_steps_per_epoch \
  48 \
  --lr \
  0.00025 \
  --lr_min \
  1e-06 \
  --wd \
  7e-05 \
  --wisig_train_shots_per_class \
  50 \
  --wisig_train_shot_strategy \
  rx_day_balanced \
  --swad_start_epoch \
  95 \
  --swad_tolerance \
  0.7 \
  --use_aug \
  --aug_scale_min \
  0.03 \
  --aug_scale_max \
  0.26 \
  --late_aug_min_scale \
  0.18 \
  --use_mixstyle \
  --mixstyle_layers \
  time_down,t1 \
  --mixstyle_mix \
  same_tx_crossdomain \
  --mixstyle_fallback \
  skip \
  --mixstyle_p \
  0.08 \
  --mixstyle_strength \
  0.28 \
  --mixstyle_late_start \
  140 \
  --mixstyle_late_ramp_epochs \
  40 \
  --mixstyle_late_min_p \
  0.036 \
  --mixstyle_late_min_strength \
  0.154 \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.54 \
  --lambda_adv \
  0.23 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.015 \
  --lambda_cons \
  0.016 \
  --lambda_group_ce \
  0.022 \
  --group_ce_mode \
  smooth_dro_capped \
  --group_ce_min_domains \
  2 \
  --group_ce_top_frac \
  0.25 \
  --groupdro_tau \
  0.5 \
  --groupdro_cap \
  0.62 \
  --use_proto_memory \
  --lambda_proto \
  0.003 \
  --proto_momentum \
  0.95 \
  --lambda_supcon_id \
  0.003 \
  --supcon_temp \
  0.12 \
  --lambda_fishr \
  0.0004 \
  --fishr_min_domains \
  2 \
  --lambda_feature_norm_guard \
  4e-05 \
  --feature_norm_guard_mode \
  l2 \
  --feature_norm_guard_target \
  0.0 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.18 \
  --sat_view_prob \
  0.18 \
  --sat_train_scenarios \
  clear_leo,mixed_orbit \
  --sat_view_schedule \
  '1@0.18:clear_leo,mixed_orbit;145@0.11:clear_leo,mixed_orbit'

run_candidate PFS15_FS080_BRIDGE32_RXDAY CEN51_PFS2_FS080_BRIDGE32_RXDAY_seed2028 pure_fewshot_lt100 6 \
  --train_mode \
  centralized \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_protocol \
  cvs_day_rx \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.5 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --wisig_max_train_per_combo \
  0 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --seed \
  2028 \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_interval \
  1 \
  --primary_udu_weight \
  0.84 \
  --no_train_drop_last \
  --batch_size \
  64 \
  --epochs \
  190 \
  --train_steps_per_epoch \
  32 \
  --lr \
  0.00025 \
  --lr_min \
  1e-06 \
  --wd \
  7e-05 \
  --wisig_train_shots_per_class \
  80 \
  --wisig_train_shot_strategy \
  rx_day_balanced \
  --swad_start_epoch \
  95 \
  --swad_tolerance \
  0.7 \
  --use_aug \
  --aug_scale_min \
  0.03 \
  --aug_scale_max \
  0.26 \
  --late_aug_min_scale \
  0.18 \
  --use_mixstyle \
  --mixstyle_layers \
  time_down,t1 \
  --mixstyle_mix \
  same_tx_crossdomain \
  --mixstyle_fallback \
  skip \
  --mixstyle_p \
  0.1 \
  --mixstyle_strength \
  0.32 \
  --mixstyle_late_start \
  140 \
  --mixstyle_late_ramp_epochs \
  40 \
  --mixstyle_late_min_p \
  0.045 \
  --mixstyle_late_min_strength \
  0.176 \
  --no_enable_pa_aux \
  --no_enable_dac_aux \
  --no_aug_enable_pa_normal \
  --lambda_cls_pa \
  0.0 \
  --lambda_pa_joint_inv \
  0.0 \
  --lambda_pa_kl \
  0.0 \
  --lambda_pa_reg \
  0.0 \
  --lambda_dom \
  0.54 \
  --lambda_adv \
  0.25 \
  --grl_lambda \
  1 \
  --lambda_orth \
  0.015 \
  --lambda_cons \
  0.016 \
  --lambda_group_ce \
  0.03 \
  --group_ce_mode \
  smooth_dro_capped \
  --group_ce_min_domains \
  2 \
  --group_ce_top_frac \
  0.25 \
  --groupdro_tau \
  0.5 \
  --groupdro_cap \
  0.62 \
  --use_proto_memory \
  --lambda_proto \
  0.004 \
  --proto_momentum \
  0.95 \
  --lambda_supcon_id \
  0.004 \
  --supcon_temp \
  0.12 \
  --lambda_fishr \
  0.0006 \
  --fishr_min_domains \
  2 \
  --lambda_feature_norm_guard \
  3e-05 \
  --feature_norm_guard_mode \
  l2 \
  --feature_norm_guard_target \
  0.0 \
  --domain_freq_stability_mode \
  off \
  --pa_orders \
  1,3,5 \
  --no_use_sat_consistency \
  --lambda_sat_cons \
  0.0 \
  --lambda_sat_cls \
  0.0 \
  --sat_cons_start_epoch \
  999 \
  --use_concat_sat_channel_aug \
  --concat_sat_ce_weight \
  0.22 \
  --sat_view_prob \
  0.22 \
  --sat_train_scenarios \
  clear_leo,mixed_orbit \
  --sat_view_schedule \
  '1@0.22:clear_leo,mixed_orbit;145@0.13:clear_leo,mixed_orbit'

run_candidate PFS16_ORIG100_CEN51_R04_R010 CEN51_ORIG100_R04_sat_joint_guard_no_overdrive_r010 restore_original_cen51_ge100 7 \
  --train_mode \
  centralized \
  --batch_size \
  256 \
  --eval_batch_size \
  256 \
  --dataset \
  wisig \
  --wisig_domain \
  rx_day \
  --wisig_train_ratio \
  0.1 \
  --wisig_split_strategy \
  random \
  --wisig_cap_strategy \
  random \
  --epochs \
  200 \
  --test_eval_policy \
  interval_final \
  --test_eval_start_epoch \
  1 \
  --test_eval_interval \
  10 \
  --eval_sat_channel \
  --eval_sat_on \
  test_unseen_day_unseen_rx \
  --eval_sat_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_eval_max_batches \
  -1 \
  --arch_family \
  cvsincnet \
  --slim_group \
  none \
  --branch_ablation \
  no_dac \
  --domain_branch_ablation \
  no_stats \
  --domain_enhancer \
  rcn_stats \
  --domain_enhancer_strength \
  0.35 \
  --exp_group \
  s3_rxrobust_no_dac \
  --model_variant \
  lite_d \
  --use_aug \
  --use_concat_sat_channel_aug \
  --concat_sat_start_epoch \
  1 \
  --lambda_sat_cls \
  0.0 \
  --lambda_sat_cons \
  0.006 \
  --seed \
  1337 \
  --use_mixstyle \
  --mixstyle_layers \
  time_down,t1 \
  --mixstyle_mix \
  same_tx_crossdomain \
  --mixstyle_fallback \
  skip \
  --mixstyle_strength \
  0.7 \
  --mixstyle_p \
  0.18 \
  --mixstyle_late_start \
  110 \
  --mixstyle_late_ramp_epochs \
  40 \
  --mixstyle_late_min_p \
  0.05 \
  --mixstyle_late_min_strength \
  0.32 \
  --sat_train_scenarios \
  clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit \
  --sat_view_prob \
  1 \
  --domain_freq_stability_mode \
  dsq \
  --freq_stability_channels \
  2 \
  --lambda_group_ce \
  0.088 \
  --group_ce_mode \
  smooth_dro_capped \
  --group_ce_top_frac \
  0.2 \
  --groupdro_tau \
  0.37 \
  --groupdro_cap \
  0.48 \
  --use_proto_memory \
  --lambda_proto \
  0.016 \
  --proto_momentum \
  0.97 \
  --lambda_supcon_id \
  0.022 \
  --supcon_temp \
  0.12 \
  --lambda_fishr \
  0.002 \
  --fishr_min_domains \
  4 \
  --generalization_feature \
  z_id \
  --collapse_guard \
  --collapse_guard_min_epoch \
  35 \
  --collapse_guard_best_margin \
  12 \
  --collapse_guard_max_skipped_delta \
  2 \
  --use_ema_ckpt \
  --ema_decay \
  0.999 \
  --use_swad_ckpt \
  --swad_start_epoch \
  70 \
  --swad_tolerance \
  0.34 \
  --primary_udu_weight \
  0.84 \
  --concat_sat_ce_weight \
  1.19 \
  --pa_orders \
  1,3,5 \
  --group_ce_min_domains \
  4 \
  --use_sat_consistency \
  --sat_cons_start_epoch \
  118 \
  --sat_view_schedule \
  '1@0.98:clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit;115@0.82:clear_leo,low_elev_leo,rain_leo,storm_mp,mixed_orbit'

echo "[CEN51-PFS2] launch submissions complete"
