"""Read back complete diagnostic artifacts and reload only this run's states."""
import argparse
import json
from pathlib import Path
import numpy as np
import torch
from runtime import load_module, expand_head

p=argparse.ArgumentParser(); p.add_argument('--method',required=True,choices=['issl','lora'])
p.add_argument('--output',required=True); args=p.parse_args(); out=Path(args.output)
resolved=json.loads((out/'resolved_config.json').read_text(encoding='utf-8'))
acceptance=json.loads((out/'acceptance.json').read_text(encoding='utf-8'))
metrics=json.loads((out/'metrics.json').read_text(encoding='utf-8'))
rows=[json.loads(line) for line in (out/'steps.jsonl').read_text(encoding='utf-8').splitlines()]
steps=[r for r in rows if not r.get('summary',False)]
assert len(steps)==acceptance['steps']
assert all(np.isfinite(r['loss']) and np.isfinite(r['grad_norm']) for r in steps)
with np.load(out/'predictions.npz',allow_pickle=False) as z:
    assert len(z['ids'])==384 and len(set(z['ids']))==384
    assert all(len(z[k])==384 for k in z.files if k!='ids')
loaded=[]
torch.set_num_threads(4)
if args.method=='issl':
    module=load_module(Path(resolved['issl_source'])/'resnet.py','issl_reload')
    for name in ['base','ssl','downstream','incremental_baseline']:
        # These four files were just generated by this registered scratch run.
        payload=torch.load(out/(name+'.pt'),map_location='cpu',weights_only=True)
        model=module.resnet18(num_classes=3,drop_out=.1)
        if name!='base': model,_=expand_head(model,3)
        model.load_state_dict(payload['state_dict'],strict=True); model.eval()
        with torch.no_grad(): logits,_=model(torch.ones(2,2,256))
        assert logits.shape==(2,3 if name=='base' else 6) and torch.isfinite(logits).all()
        loaded.append(name+'.pt')
    assert len([r for r in steps if r['stage']=='ssl'])==18
    assert all(r['kd_student_gradient'] is False and r['zero_grad'] is False for r in steps if r['stage']=='ssl')
else:
    module=load_module(Path(resolved['lora_torch_source'])/'Openset_RFFI/deep_learning_models.py','lora_reload')
    payload=torch.load(out/'extractor.pt',map_location='cpu',weights_only=True)
    model=module.FeatureExtractor(input_shape=payload['input_shape'])
    model.load_state_dict(payload['state_dict'],strict=True); model.eval()
    with torch.no_grad(): embeddings=model(torch.ones(2,1,26,6))
    assert embeddings.shape==(2,512) and torch.isfinite(embeddings).all()
    loaded=['extractor.pt']
result={'status':'VERIFIED','method':args.method,'steps':len(steps),'prediction_ids':384,
        'checkpoint_reload_strict':loaded,'all_step_losses_gradients_finite':True,
        'claim_scope':'functional acceptance only; no new training or performance selection'}
(out/'artifact_audit.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps(result))
